# Generated by Django 4.2.3 on 2023-07-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murabei_api', '0003_booksubjects_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksubjects',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='booksubjects',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='booksubjects',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='murabei_api.book'),
        ),
        migrations.AddField(
            model_name='booksubjects',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='murabei_api.subject'),
        ),
    ]
