# Generated by Django 4.2.3 on 2023-07-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murabei_api', '0005_rename_booksubjects_booksubject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookSubject',
            new_name='BookSubjects',
        ),
    ]
