# Generated by Django 4.2.3 on 2023-07-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murabei_api', '0006_rename_booksubject_booksubjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksubjects',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='booksubjects',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
