# Generated by Django 4.2.3 on 2023-07-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murabei_api', '0007_rename_book_booksubjects_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksubjects',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='booksubjects',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
